[build]
  command = "cd PerformaSync && npm install && npm run build -- --prod"

  # Set the base directory for the build
  base = "PerformaSync"

  # Publish directory for the build output
  publish = "dist/browser"



# Add redirects if needed
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
